# Generated by Django 3.2.7 on 2021-10-03 17:44

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_deviсe', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('dev_eui', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('last_action_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('deviсe_type', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_meter', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('first_action_time', models.DateTimeField(auto_now_add=True)),
                ('initial_value', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='core.device')),
            ],
        ),
    ]
