# Generated by Django 3.2.7 on 2021-09-23 13:15

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_city', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_deviсe', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('dev_eui', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('last_action_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('deviсe_type', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_street', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_devise', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('first_action_time', models.DateTimeField(auto_now_add=True)),
                ('initial_value', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_house', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='core.street')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_district', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='core.city')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='locate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.house'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_apartment', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='core.house')),
            ],
        ),
    ]
