# Generated by Django 3.2.7 on 2021-10-03 17:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Node',
            new_name='City',
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='core.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.street')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.city'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.house')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='apartment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.apartment'),
            preserve_default=False,
        ),
    ]
