# Generated by Django 3.2.7 on 2021-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='locate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='street',
            name='locate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='core.district'),
        ),
    ]
