# Generated by Django 3.2.7 on 2021-09-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210928_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='uuid_devise',
            new_name='uuid_meter',
        ),
    ]
