# Generated by Django 3.2.7 on 2021-09-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_uuid_devise_meter_uuid_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='locate',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='locate',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='locate',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='locate',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='locate',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='locate',
            new_name='district',
        ),
    ]
