# Generated by Django 3.2.7 on 2021-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210929_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
