# Generated by Django 3.2.7 on 2021-10-11 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20211010_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='meter',
            name='owner',
        ),
        migrations.AddField(
            model_name='meter',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
