# Generated by Django 3.2.7 on 2021-09-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_apartment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='owner',
        ),
    ]
