# Generated by Django 3.2.7 on 2021-10-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211011_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='full_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='apartment',
            name='part_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='full_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='part_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='district',
            name='full_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='district',
            name='part_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='house',
            name='full_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='house',
            name='part_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='street',
            name='full_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='street',
            name='part_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
