# Generated by Django 3.2.7 on 2021-10-12 09:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20211012_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='full_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='owner',
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='part_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='city',
            name='full_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='city',
            name='owner',
        ),
        migrations.AddField(
            model_name='city',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='part_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='full_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='district',
            name='owner',
        ),
        migrations.AddField(
            model_name='district',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='district',
            name='part_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='house',
            name='full_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='part_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='meter',
            name='owner',
        ),
        migrations.AddField(
            model_name='meter',
            name='owner',
            field=models.ForeignKey(blank=True, default=1.0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='street',
            name='full_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
        migrations.RemoveField(
            model_name='street',
            name='owner',
        ),
        migrations.AddField(
            model_name='street',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='street',
            name='part_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
    ]
