# Generated by Django 3.2.7 on 2021-10-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apartment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='uuid_apartment',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='uuid_city',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='uuid_deviсe',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='uuid_district',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='uuid_house',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='uuid_meter',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='uuid_street',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.house'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.city'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='core.district'),
        ),
    ]
