# Generated by Django 3.2.7 on 2021-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211012_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='full_owner',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='part_owner',
        ),
        migrations.RemoveField(
            model_name='city',
            name='full_owner',
        ),
        migrations.RemoveField(
            model_name='city',
            name='part_owner',
        ),
        migrations.RemoveField(
            model_name='district',
            name='full_owner',
        ),
        migrations.RemoveField(
            model_name='district',
            name='part_owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='full_owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='part_owner',
        ),
        migrations.RemoveField(
            model_name='street',
            name='full_owner',
        ),
        migrations.RemoveField(
            model_name='street',
            name='part_owner',
        ),
    ]
